### PR TITLE
test_aix2john.py: Unit test of aix2john.py

### PR DESCRIPTION
**Pull request by tsvenbla**
A unit test consisting of 11 test cases against the aix2john.py file. Adheres to PEP8 standard.

### CODE REVIEW

**Comment by tsvenbla** [comment]
Added a unit test (consisting of 11 use cases currently) and two bogus `passwd` files with hashes of the word `password`.

**Comment by solardiz** [comment]
While sample inputs do belong in this repo, I'm not sure about test scripts and even less so about having in here a copy of the script being tested. Further, the script being tested is yet being discussed/revised/reconsidered in a currently open PR to `john`. So I'll wait on deciding what to do here until we're done with that other PR.

We have https://github.com/openwall/john-tests for external tests of `john` itself. Maybe we should start adding external tests of scripts to there as well? Or maybe they should be in a subdirectory of the main `john` tree? We're undecided. @magnumripper @claudioandre-br @jfoug

**Comment by claudioandre-br** [comment]
> We have https://github.com/openwall/john-tests for external tests of `john` itself.

I vote to separate the responsibilities, I mean, move/create all these scripts in `john-tests`. `john` itself must concentrate on what it must do. 

BTW: I also see `2john` scripts/tools in a new (john-2john) repository.

> Maybe we should start adding external tests of scripts to there as well?

Sure.

**Comment by magnumripper** [comment]
> > We have https://github.com/openwall/john-tests for external tests of `john` itself.
> 
> I vote to separate the responsibilities, I mean, move/create all these scripts in `john-tests`. `john` itself must concentrate on what it must do.

Agreed and we could even move `pass_gen.pl` to that repo.

OTOH, that repo (as well as `pass_gen.pl`) is an utter mess, with (among other problems) really terrible spaghetti perl code. We (as in "someone") should rewrite or at least do a major clean-up of `pass_gen.pl`, and `jtrts.pl` should definitely be rewritten from scratch (and all the current test files should be dropped). I could list pretty detailed ideas about how to drastically improve both.

> BTW: I also see `2john` scripts/tools in a new (john-2john) repository.

Where? I can guess why - users of hashcat very often use 2john scripts and the main hashcat repo doesn't hold any conversion tools. Perhaps we should move all 2john tools to this/a new repo (syncing thoughts with hashcat team) and hope for some more volunteer work with them. Then again, the hashcat folks have some ideas about system requirements that we do not - they are much less concerned about backward compatibility in general (and likely with python2 in particular).

**Comment by solardiz** [comment]
I dislike the idea of splitting 2john tools into their own repo. It's important to have compatible versions of those and `john` itself in the same repo at each commit and in each release.

As to tests, I agree our current `john-tests` should stay separate, but if we could have cleaner implementations of some (other) tests without needing large input files, it'd be useful to have them in the main `john` repo and invoked by `make check`, which distro packages could easily run at package build time.

**Pull request closed without merging**
